---
title: Your awesome title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: http://example.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
gems:
- kramdown
- jekyll-multiple-languages-plugin
languages:
- pt
- en
- es
exclude:
- config.ru
- Gemfile
- Gemfile.lock
- vendor
- Procfile
- Rakefile
exclude_from_localizations:
- javascript
- images
- css
authors:
  tom:
    name: Tom Canabarro
    image: "/img/authors/tc.jpg"
    bio: Co-founder @ Konduto
    link: http://br.linkedin.com/in/tcanabarro/
  milton:
    name: Milton Tavares Neto
    image: "/img/authors/mt.jpg"
    bio: Co-founder @ Konduto
    link: http://br.linkedin.com/in/miltontavares/
  felipe:
    name: Felipe Held
    image: "/img/authors/fh.jpg"
    bio: Head of Marketing & Communications @ Konduto
    link: https://br.linkedin.com/in/felipeheld
  daniel:
    name: Daniel Bento
    image: "/img/authors/db.jpg"
    bio: Co-founder @ Konduto
    link: https://br.linkedin.com/in/danielbento
